package com.jk.bean;

import java.io.Serializable;
import java.util.List;

public class Tree implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree.id
     *
     * @mbggenerated Mon Jan 21 16:07:41 CST 2019
     */
    private Integer id = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree.text
     *
     * @mbggenerated Mon Jan 21 16:07:41 CST 2019
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree.href
     *
     * @mbggenerated Mon Jan 21 16:07:41 CST 2019
     */
    private String href;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tree.pid
     *
     * @mbggenerated Mon Jan 21 16:07:41 CST 2019
     */
    private Integer pid = 0;

    private String state;

    private boolean checked;

    private String flag;

    private List<Tree> children;

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public List<Tree> getChildren() {
        return children;
    }

    public void setChildren(List<Tree> children) {
        this.children = children;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getHref() {
        return href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public Integer getPid() {
        return pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }
}