package com.jk.bean;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.Id
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_mch
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhMch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_nch
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhNch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_mm
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhMm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_xm
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhXm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_shjh
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhShjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_yx
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhYx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_tx
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private String yhTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_user_account.yh_jb
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    private Integer yhJb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.Id
     *
     * @return the value of t_mall_user_account.Id
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.Id
     *
     * @param id the value for t_mall_user_account.Id
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_mch
     *
     * @return the value of t_mall_user_account.yh_mch
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhMch() {
        return yhMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_mch
     *
     * @param yhMch the value for t_mall_user_account.yh_mch
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhMch(String yhMch) {
        this.yhMch = yhMch == null ? null : yhMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_nch
     *
     * @return the value of t_mall_user_account.yh_nch
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhNch() {
        return yhNch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_nch
     *
     * @param yhNch the value for t_mall_user_account.yh_nch
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhNch(String yhNch) {
        this.yhNch = yhNch == null ? null : yhNch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_mm
     *
     * @return the value of t_mall_user_account.yh_mm
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhMm() {
        return yhMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_mm
     *
     * @param yhMm the value for t_mall_user_account.yh_mm
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhMm(String yhMm) {
        this.yhMm = yhMm == null ? null : yhMm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_xm
     *
     * @return the value of t_mall_user_account.yh_xm
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhXm() {
        return yhXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_xm
     *
     * @param yhXm the value for t_mall_user_account.yh_xm
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhXm(String yhXm) {
        this.yhXm = yhXm == null ? null : yhXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_shjh
     *
     * @return the value of t_mall_user_account.yh_shjh
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhShjh() {
        return yhShjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_shjh
     *
     * @param yhShjh the value for t_mall_user_account.yh_shjh
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhShjh(String yhShjh) {
        this.yhShjh = yhShjh == null ? null : yhShjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_yx
     *
     * @return the value of t_mall_user_account.yh_yx
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhYx() {
        return yhYx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_yx
     *
     * @param yhYx the value for t_mall_user_account.yh_yx
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhYx(String yhYx) {
        this.yhYx = yhYx == null ? null : yhYx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_tx
     *
     * @return the value of t_mall_user_account.yh_tx
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public String getYhTx() {
        return yhTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_tx
     *
     * @param yhTx the value for t_mall_user_account.yh_tx
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhTx(String yhTx) {
        this.yhTx = yhTx == null ? null : yhTx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_user_account.yh_jb
     *
     * @return the value of t_mall_user_account.yh_jb
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public Integer getYhJb() {
        return yhJb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_user_account.yh_jb
     *
     * @param yhJb the value for t_mall_user_account.yh_jb
     *
     * @mbggenerated Mon Jan 21 14:57:09 CST 2019
     */
    public void setYhJb(Integer yhJb) {
        this.yhJb = yhJb;
    }
}